from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from pydantic import BaseModel

load_dotenv()


class DocumentMetadata(BaseModel):
    """Fields the retrieval API actually returns for a chunk.

    A subject_tags list used to be extracted here too. Nothing ever read it,
    but it was generated by the model on every ingest and then copied onto
    every chunk of the document -- so a 500-chunk judgment stored 500 copies of
    a list no query looked at.
    """

    title: str
    document_type: str
    date: str


def extract_metadata(front_matter_text):
    llm = ChatOpenAI(model="gpt-4o-mini").with_structured_output(DocumentMetadata)
    return llm.invoke(front_matter_text)
