/**
 * Downscales and recompresses the JPEGs in public/images.
 *
 * The source photos were 2000-2400px wide originals (the hero was ~2MB). Nothing
 * on the site renders them above ~40vw, so the extra pixels only ever cost us
 * time: on Vercel every new width/format combination is transcoded on demand,
 * and a cold miss on a 2MB source took ~3.5s before the image appeared. Locally
 * that cost is invisible, which is why this only ever looked broken in prod.
 *
 * Run with `npm run optimize:images` after adding or replacing a photo.
 */
import sharp from "sharp";
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const IMAGE_DIR = path.join(process.cwd(), "public", "images");
const PLACEHOLDER_FILE = path.join(process.cwd(), "lib", "image-placeholders.ts");

// Max width each image is ever asked to render at, x2 for high-DPI screens.
const MAX_WIDTHS = {
  "hero-paris-louvre.jpg": 1600, // 40vw column, aspect-[3/4]
  "why-choose-palais-garnier.jpg": 1400, // 40vw column, aspect-[4/5]
  "auth-mountain-bg.jpg": 1920, // full-bleed auth background
  "waitlist-pont-alexandre.jpg": 1600, // full-bleed, sits under an 85% overlay
};

const DEFAULT_MAX_WIDTH = 1600;
const QUALITY = 80;

const kb = (bytes) => `${(bytes / 1024).toFixed(0)} KB`;

const files = (await readdir(IMAGE_DIR)).filter((f) => /\.jpe?g$/i.test(f));
let before = 0;
let after = 0;
const placeholders = {};

for (const file of files) {
  const filePath = path.join(IMAGE_DIR, file);
  const original = await readFile(filePath);
  const maxWidth = MAX_WIDTHS[file] ?? DEFAULT_MAX_WIDTH;

  // Re-encoding an already-processed JPEG just loses a little more detail each
  // run, so treat "small enough and narrow enough" as already done.
  const meta = await sharp(original).metadata();
  const bytesPerPixel = original.length / (meta.width * meta.height);
  if (meta.width <= maxWidth && bytesPerPixel < 0.35) {
    console.log(`  skip  ${file.padEnd(32)} already ${meta.width}px / ${kb(original.length)}`);
    before += original.length;
    after += original.length;
    placeholders[`/images/${file}`] =
      `data:image/jpeg;base64,${(await sharp(original).resize({ width: 12 }).jpeg({ quality: 50 }).toBuffer()).toString("base64")}`;
    continue;
  }

  const optimized = await sharp(original)
    .resize({ width: maxWidth, withoutEnlargement: true })
    .jpeg({ quality: QUALITY, progressive: true, mozjpeg: true })
    .toBuffer();

  // Never regress: keep whichever is smaller.
  const kept = optimized.length < original.length ? optimized : original;
  if (kept === optimized) {
    await writeFile(filePath, optimized);
    const saved = (1 - optimized.length / original.length) * 100;
    console.log(
      `  ok    ${file.padEnd(32)} ${kb(original.length)} -> ${kb(optimized.length)}  (-${saved.toFixed(0)}%)`,
    );
  } else {
    console.log(`  skip  ${file.padEnd(32)} already ${kb(original.length)}`);
  }
  before += original.length;
  after += kept.length;

  // A 12px-wide preview, inlined as the blur placeholder so the layout is never
  // a bare grey box while the real image is still being fetched.
  const preview = await sharp(kept).resize({ width: 12 }).jpeg({ quality: 50 }).toBuffer();
  placeholders[`/images/${file}`] = `data:image/jpeg;base64,${preview.toString("base64")}`;
}

const entries = Object.entries(placeholders)
  .map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`)
  .join("\n");

await writeFile(
  PLACEHOLDER_FILE,
  `// Generated by scripts/optimize-images.mjs -- do not edit by hand.\n` +
    `// Run \`npm run optimize:images\` to regenerate.\n\n` +
    `export const imageBlurDataURL: Record<string, string> = {\n${entries}\n};\n`,
  "utf8",
);

console.log(`\ntotal   ${kb(before)} -> ${kb(after)}  (-${((1 - after / before) * 100).toFixed(0)}%)`);
console.log(`blur    ${Object.keys(placeholders).length} placeholders -> lib/image-placeholders.ts`);
