import { NextRequest, NextResponse } from "next/server"
import Client from "../../lib/models/client"
import User from "../../lib/models/user"
import connectMongoWithRetry from "../../lib/db/connectMongo"
import Case from "../../lib/models/case";
import { ensureUser } from "../../lib/ensureUser";
import { requireOwnedClient, requireUserContext } from "@/app/api/lib/routeGuards";
import { createClientSchema, updateClientSchema } from "@/app/api/lib/validators/userdetails";
import { canAccessFirm, type TeamPermission } from "@/app/api/lib/services/rbac";

function getClientNameFromCase(caseTitle?: string, caseNo?: string) {
    const normalizedTitle = (caseTitle || "").trim()
    if (normalizedTitle) {
        const [partyName] = normalizedTitle.split(/\b(?:vs\.?|versus|v\/s)\b/i)
        const cleaned = (partyName || "").replace(/\s+/g, " ").trim()
        if (cleaned.length >= 3) return cleaned
        return normalizedTitle
    }
    return caseNo ? `Client ${caseNo}` : "Case Client"
}

function getAutoGeneratedEmail(caseNo: string | undefined, caseId: string) {
    const slug = (caseNo || caseId || "client")
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, ".")
        .replace(/^\.+|\.+$/g, "")
        .slice(0, 40)
    const suffix = caseId.slice(-6)
    return `${slug || "case.client"}.${suffix}@autoclient.lexvert.local`
}

async function ensureClientsSyncedFromCases(userId: string) {
    const user = await User.findOne({ clerkUid: userId })
        .select("clients cases")
        .populate("cases")
        .exec()

    if (!user || !Array.isArray(user.cases) || user.cases.length === 0) return

    const alreadyOnUser = new Set(
        (user.clients || []).map((clientId: any) => clientId.toString())
    )
    const clientIdsToAttach = new Set<string>()

    for (const caseDoc of user.cases as any[]) {
        const linkedClientIds = Array.isArray(caseDoc.clients)
            ? caseDoc.clients.map((clientId: any) => clientId.toString())
            : []

        if (linkedClientIds.length > 0) {
            linkedClientIds.forEach((clientId: string) => clientIdsToAttach.add(clientId))
            continue
        }

        const caseId = caseDoc._id.toString()
        const minimalClient = await Client.create({
            salutation: "mr",
            name: getClientNameFromCase(caseDoc.caseTitle, caseDoc.caseNo),
            company: "",
            group: "",
            email: getAutoGeneratedEmail(caseDoc.caseNo, caseId),
            contact: "0000000000",
            alternateContact: "",
            gstin: "",
            address: {},
            customFields: [],
            notes: [],
            cases: [caseDoc._id],
        })

        await Case.findByIdAndUpdate(caseDoc._id, {
            $addToSet: { clients: minimalClient._id },
        })

        clientIdsToAttach.add(minimalClient._id.toString())
    }

    const missingClientIds = Array.from(clientIdsToAttach).filter((clientId) => !alreadyOnUser.has(clientId))
    if (missingClientIds.length > 0) {
        await User.findOneAndUpdate(
            { clerkUid: userId },
            { $addToSet: { clients: { $each: missingClientIds } } }
        )
    }
}

export async function GET(req: NextRequest) {
    try {
        const userContext = await requireUserContext();
        if (userContext instanceof NextResponse) {
            return userContext;
        }

        await connectMongoWithRetry()
        const userId = userContext.clerkUid;
        await ensureUser(userId);
        const scope = req.nextUrl.searchParams.get("scope")
        const actorUser = await User.findOne({ clerkUid: userId }).select("primaryFirmId").lean().exec()
        const actorFirmId = (actorUser as any)?.primaryFirmId ? (actorUser as any).primaryFirmId.toString() : null

        const clientId = req.nextUrl.searchParams.get("id")
        if (clientId) {
            const clientDoc = await Client.findById(clientId)
                .populate("cases", "_id caseTitle caseNo status courtDate courtName")
                .populate("notes", "_id title content createdAt updatedAt")
                .lean()
                .exec()

            if (!clientDoc) {
                return NextResponse.json({ error: "Client not found" }, { status: 404 })
            }

            const isOwnedClient = await requireOwnedClient(userId, clientId)
            let hasFirmAccess = false

            if (!isOwnedClient && (clientDoc as any).firmId) {
                const firmAccess = await canAccessFirm(
                    userId,
                    (clientDoc as any).firmId.toString(),
                    "client.read" as TeamPermission,
                )
                hasFirmAccess = firmAccess.allowed
            }

            if (!isOwnedClient && !hasFirmAccess) {
                return NextResponse.json({ error: "Client not found" }, { status: 404 })
            }

            // Only fetch necessary fields for single client
            return NextResponse.json({ client: clientDoc })
        }

        if (scope === "firm" && actorFirmId) {
            const firmAccess = await canAccessFirm(userId, actorFirmId, "client.read" as TeamPermission)
            if (!firmAccess.allowed) {
                return NextResponse.json({ error: "Forbidden" }, { status: 403 })
            }

            const firmClients = await Client.find({ firmId: actorFirmId })
                .populate({
                    path: "cases",
                    select: "_id caseTitle caseNo status courtDate courtName",
                })
                .populate({
                    path: "notes",
                    select: "_id title content createdAt updatedAt",
                })
                .lean()
                .exec()

            return NextResponse.json({
                userClients: {
                    clients: firmClients,
                },
                scope: "firm",
            })
        }

        if (userId) {
            await ensureClientsSyncedFromCases(userId)
        }
        
        // For list view, use lean() and select necessary fields for display
        const userClients = await User.findOne( {clerkUid: userId} )
            .populate({
                path: "clients",
                populate: [
                    { path: "cases", select: "_id caseTitle caseNo status courtDate courtName" },
                    { path: "notes", select: "_id title content createdAt updatedAt" },
                ],
            })
            .lean()
            .exec()

        return NextResponse.json({ userClients })
    } catch (error) {
        console.error(error)
        return NextResponse.json({ error: "Failed to connect to database" }, { status: 500 })
    }
}

export async function POST(req: NextRequest) {
    try {
        const userContext = await requireUserContext();
        if (userContext instanceof NextResponse) {
            return userContext;
        }

        await connectMongoWithRetry()
        const userId = userContext.clerkUid;
        await ensureUser(userId);

        const rawBody = (await req.json().catch(() => null)) as Record<string, unknown> | null
        if (!rawBody) {
            return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 })
        }

        const parsed = createClientSchema.safeParse(rawBody)
        if (!parsed.success) {
            const issue = parsed.error.issues[0]?.message || "Invalid client payload"
            return NextResponse.json({ error: issue }, { status: 400 })
        }

        const ownerUser = await User.findOne({ clerkUid: userId }).select("primaryFirmId").lean().exec()

        const client = new Client({
            ...parsed.data,
            firmId: (ownerUser as any)?.primaryFirmId || null,
        })
        await client.save()
        const userClients = await User.findOneAndUpdate( {clerkUid: userId}, { $push: { clients: client._id } }, { new: true } )
        return NextResponse.json({ userClients, clientId: client._id })
    } catch (error) {
        console.error(error)
        return NextResponse.json({ error: "Failed to connect to database" }, { status: 500 })
    }
}

export async function PUT(req: NextRequest) {
    try {
        const userContext = await requireUserContext();
        if (userContext instanceof NextResponse) {
            return userContext;
        }

        await connectMongoWithRetry()
        const rawBody = (await req.json().catch(() => null)) as Record<string, unknown> | null
        if (!rawBody) {
            return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 })
        }

        const parsed = updateClientSchema.safeParse(rawBody)
        if (!parsed.success) {
            const issue = parsed.error.issues[0]?.message || "Invalid client payload"
            return NextResponse.json({ error: issue }, { status: 400 })
        }

        const isOwnedClient = await requireOwnedClient(userContext.clerkUid, parsed.data._id)
        if (!isOwnedClient) {
            return NextResponse.json({ error: "Client not found" }, { status: 404 })
        }

        const { _id, ...updateData } = parsed.data
        const client = await Client.findByIdAndUpdate(_id, updateData, { new: true })
        return NextResponse.json({ client })
    } catch (error) {
        console.error(error)
        return NextResponse.json({ error: "Failed to connect to database" }, { status: 500 })
    }
}

export async function DELETE(req: NextRequest) {
    try {
        const userContext = await requireUserContext();
        if (userContext instanceof NextResponse) {
            return userContext;
        }

        await connectMongoWithRetry()
        const userId = userContext.clerkUid;
        const clientId = req.nextUrl.searchParams.get("id")

        if (!clientId) {
            return NextResponse.json({ error: "Client ID required" }, { status: 400 })
        }

        const isOwnedClient = await requireOwnedClient(userId, clientId)
        if (!isOwnedClient) {
            return NextResponse.json({ error: "Client not found" }, { status: 404 })
        }

        const client = await Client.findByIdAndDelete(clientId)
        if (!client) {
            return NextResponse.json({ error: "Client not found" }, { status: 404 })
        }

        const userClients = await User.findOneAndUpdate( {clerkUid: userId}, { $pull: { clients: client._id } }, { new: true } )
        return NextResponse.json({ userClients })
    } catch (error) {
        console.error(error)
        return NextResponse.json({ error: "Failed to connect to database" }, { status: 500 })
    }
}
