import { NextRequest, NextResponse } from "next/server"
import Client from "../../lib/models/client"
import User from "../../lib/models/user"
import connectMongoWithRetry from "../../lib/db/connectMongo"
import { auth } from "@clerk/nextjs/server";
import Case from "../../lib/models/case";
import { ensureUser } from "../../lib/ensureUser";

function getClientNameFromCase(caseTitle?: string, caseNo?: string) {
    const normalizedTitle = (caseTitle || "").trim()
    if (normalizedTitle) {
        const [partyName] = normalizedTitle.split(/\b(?:vs\.?|versus|v\/s)\b/i)
        const cleaned = (partyName || "").replace(/\s+/g, " ").trim()
        if (cleaned.length >= 3) return cleaned
        return normalizedTitle
    }
    return caseNo ? `Client ${caseNo}` : "Case Client"
}

function getAutoGeneratedEmail(caseNo: string | undefined, caseId: string) {
    const slug = (caseNo || caseId || "client")
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, ".")
        .replace(/^\.+|\.+$/g, "")
        .slice(0, 40)
    const suffix = caseId.slice(-6)
    return `${slug || "case.client"}.${suffix}@autoclient.lexvert.local`
}

async function ensureClientsSyncedFromCases(userId: string) {
    const user = await User.findOne({ clerkUid: userId })
        .select("clients cases")
        .populate("cases")
        .exec()

    if (!user || !Array.isArray(user.cases) || user.cases.length === 0) return

    const alreadyOnUser = new Set(
        (user.clients || []).map((clientId: any) => clientId.toString())
    )
    const clientIdsToAttach = new Set<string>()

    for (const caseDoc of user.cases as any[]) {
        const linkedClientIds = Array.isArray(caseDoc.clients)
            ? caseDoc.clients.map((clientId: any) => clientId.toString())
            : []

        if (linkedClientIds.length > 0) {
            linkedClientIds.forEach((clientId: string) => clientIdsToAttach.add(clientId))
            continue
        }

        const caseId = caseDoc._id.toString()
        const minimalClient = await Client.create({
            salutation: "mr",
            name: getClientNameFromCase(caseDoc.caseTitle, caseDoc.caseNo),
            company: "",
            group: "",
            email: getAutoGeneratedEmail(caseDoc.caseNo, caseId),
            contact: "0000000000",
            alternateContact: "",
            gstin: "",
            address: {},
            customFields: [],
            notes: [],
            cases: [caseDoc._id],
        })

        await Case.findByIdAndUpdate(caseDoc._id, {
            $addToSet: { clients: minimalClient._id },
        })

        clientIdsToAttach.add(minimalClient._id.toString())
    }

    const missingClientIds = Array.from(clientIdsToAttach).filter((clientId) => !alreadyOnUser.has(clientId))
    if (missingClientIds.length > 0) {
        await User.findOneAndUpdate(
            { clerkUid: userId },
            { $addToSet: { clients: { $each: missingClientIds } } }
        )
    }
}

export async function GET(req: NextRequest) {
    try {
        await connectMongoWithRetry()
        const { userId } = await auth();
        if (userId) await ensureUser(userId);

        const clientId = req.nextUrl.searchParams.get("id")
        if (clientId) {
            // Only fetch necessary fields for single client
            let client = await Client.findById(clientId)
                .populate("cases", "_id caseTitle caseNo status courtDate courtName")
                .populate("notes", "_id title content createdAt updatedAt")
                .lean()
                .exec()

            return NextResponse.json({ client })
        }

        if (userId) {
            await ensureClientsSyncedFromCases(userId)
        }
        
        // For list view, use lean() and select necessary fields for display
        const userClients = await User.findOne( {clerkUid: userId} )
            .populate({
                path: "clients",
                populate: [
                    { path: "cases", select: "_id caseTitle caseNo status courtDate courtName" },
                    { path: "notes", select: "_id title content createdAt updatedAt" },
                ],
            })
            .lean()
            .exec()

        return NextResponse.json({ userClients })
    } catch (error) {
        console.error(error)
        return NextResponse.json({ error: "Failed to connect to database" }, { status: 500 })
    }
}

export async function POST(req: NextRequest) {
    try {
        await connectMongoWithRetry()
        const { userId } = await auth();
        if (userId) await ensureUser(userId);
        const clientData = await req.json()
        const client = new Client(clientData)
        await client.save()
        const userClients = await User.findOneAndUpdate( {clerkUid: userId}, { $push: { clients: client._id } }, { new: true } )
        return NextResponse.json({ userClients, clientId: client._id })
    } catch (error) {
        console.error(error)
        return NextResponse.json({ error: "Failed to connect to database" }, { status: 500 })
    }
}

export async function PUT(req: NextRequest) {
    try {
        await connectMongoWithRetry()
        const clientData = await req.json()
        const client = await Client.findByIdAndUpdate(clientData._id, clientData)
        return NextResponse.json({ client })
    } catch (error) {
        console.error(error)
        return NextResponse.json({ error: "Failed to connect to database" }, { status: 500 })
    }
}

export async function DELETE(req: NextRequest) {
    try {
        await connectMongoWithRetry()
        const { userId } = await auth();
        const clientId = req.nextUrl.searchParams.get("id")
        const client = await Client.findByIdAndDelete(clientId)
        const userClients = await User.findOneAndUpdate( {clerkUid: userId}, { $pull: { clients: client._id } }, { new: true } )
        return NextResponse.json({ userClients })
    } catch (error) {
        console.error(error)
        return NextResponse.json({ error: "Failed to connect to database" }, { status: 500 })
    }
}
